name: test
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install ".[test]"
      - run: bandit --configfile pyproject.toml --recursive .
      - run: black --check .
      - run: codespell --skip="*.tap" --skip "*.xml"  # --ignore-words-list="" 
      - run: flake8 . --max-complexity=24 --max-line-length=88 --show-source --statistics
      - run: isort --check-only .
      - run: mypy .
      - run: pytest -vv .
      - run: pytest --doctest-modules .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
